import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 41,
    paddingTop: 60,
    paddingLeft: 50,
    paddingRight: 50,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 61,
    paddingRight: 64,
  },
  view4: {
    width: 30,
    height: 30,
    borderColor: '#6A4029',
    backgroundColor: '#FFFFFF',
    borderWidth: 11,
    borderRadius: 15,
  },
  view5: {
    width: 48,
    height: 0,
    borderColor: '#E0E0E2',
    borderWidth: 1,
  },
  view6: {flexDirection: 'row', alignItems: 'center'},
  view7: {
    width: 30,
    height: 30,
    borderColor: '#9F9F9F40',
    backgroundColor: '#FFFFFF',
    borderWidth: 11,
    borderRadius: 15,
  },
  view8: {alignItems: 'center'},
  view9: {width: '100%', marginBottom: 91},
  view10: {
    width: 74,
    height: 64,
    backgroundColor: '#E0E0E2',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    marginRight: 20,
  },
  view11: {flexDirection: 'row', width: '100%', marginBottom: 53},
  view12: {
    borderBottomColor: '#E0E0E2',
    borderBottomWidth: 1,
    width: 223.02,
  },
  view13: {alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center'},
  view14: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
    height: 50,
    backgroundColor: '#000000',
    borderRadius: 25,
  },
  text1: {
    top: 35,
    position: 'absolute',
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
  },
  text2: {
    textAlign: 'center',
    width: 58,
    top: 35,
    position: 'absolute',
    color: '#9F9F9F',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
  },
  text3: {
    color: '#000000',
    fontWeight: '400',
    fontSize: 18,
    lineHeight: 27,
  },
  text4: {
    color: '#000000',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
  },
  text5: {alignSelf: 'flex-start', marginBottom: 38},
  text6: {fontWeight: '700', fontSize: 12, lineHeight: 18, color: '#000000'},
  text7: {
    fontWeight: '400',
    fontSize: 20,
    lineHeight: 30,
    color: '#9F9F9F',
    marginBottom: 10,
  },
  text8: {
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 30,
    color: '#000000',
    marginBottom: 11,
  },
  text9: {
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#000000',
    marginRight: 26,
  },
  input1: {
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 26,
    color: '#000000',
    opacity: 0.5,
  },
  image1: {width: 24, height: 24},
  image2: {width: 30, height: 30},
  image3: {width: 23, height: 23},
  btn1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 314,
    height: 70,
    backgroundColor: '#6A4029',
    borderRadius: 20,
  },
});

export default styles;
