import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 65,
    paddingTop: 57,
    paddingLeft: 41,
    paddingRight: 49,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 40,
  },
  view4: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    width: '100%',
    paddingLeft: 12,
    paddingRight: 14.3,
    paddingTop: 19,
    paddingBottom: 14,
    marginBottom: 31,
  },
  view5: {
    borderWidth: 1,
    borderColor: '#D6D9DC',
    width: '100%',
    marginBottom: 13,
  },
  view6: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFBA33',
    marginRight: 9,
  },
  view7: {flexDirection: 'row', alignItems: 'center', marginRight: 26.84},
  view8: {flexDirection: 'row'},
  view9: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#6A4029',
    marginRight: 9,
  },
  view10: {flexDirection: 'row', alignItems: 'center'},
  view11: {
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    borderRadius: 12,
    width: '100%',
    paddingTop: 22,
    paddingBottom: 30.5,
    marginBottom: 66,
  },
  view12: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    width: '100%',
    paddingLeft: 5,
    paddingRight: 22.3,
    paddingTop: 17,
    paddingBottom: 21,
    marginBottom: 47,
  },
  view13: {
    width: 163,
    height: 161.93,
    borderWidth: 20,
    borderColor: '#FFBA33',
    borderRadius: 81.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  view14: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#147AD6',
    marginRight: 10,
  },
  view15: {flexDirection: 'row'},
  view16: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(115, 136, 169, 0.353283)',
    marginRight: 10,
  },
  view17: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(115, 136, 169, 0.353283)',
  },
  text1: {
    alignSelf: 'flex-start',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 30,
    color: '#000000',
    marginLeft: 82,
  },
  text2: {
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 33,
    color: '#000000',
    marginBottom: 5,
    marginLeft: 7,
  },
  text3: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: '#7C828A',
    marginBottom: 43,
    marginLeft: 7,
  },
  text4: {
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 15,
    color: '#7C828A',
  },
  text5: {
    fontWeight: '700',
    fontSize: 28,
    lineHeight: 42,
    marginBottom: 1,
    marginLeft: 11,
    color: '#000000',
  },
  text6: {
    fontWeight: '400',
    marginLeft: 11,
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 36,
    color: '#7C828A',
  },
  text7: {
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 30.01,
    marginBottom: 8,
    color: '#000000',
  },
  text8: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 40,
    color: '#7C828A',
  },
  text9: {fontWeight: '700', fontSize: 22, lineHeight: 30, color: '#000000'},
  text10: {fontWeight: '700', fontSize: 17, lineHeight: 25.5, color: '#FFFFFF'},
  image2: {marginBottom: 23},
  btn1: {
    width: '100%',
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6A4029',
    borderRadius: 20,
  },
});

export default styles;
