import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 69,
    paddingTop: 60,
    paddingLeft: 41,
    paddingRight: 49.99,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
    paddingRight: 106.01,
  },
  view4: {
    bottom: -1,
    right: -4,
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: '#6A4029',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  view5: {marginBottom: 44},
  view6: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 27,
  },
  view7: {width: '100%', alignItems: 'center', flexDirection: 'row'},
  view8: {
    borderWidth: 1,
    borderColor: '#6A4029',
    width: 15,
    height: 15,
    borderRadius: 7.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  view9: {
    width: 7.5,
    height: 7.5,
    borderRadius: 3.75,
    backgroundColor: '#6A4029',
  },
  view10: {
    borderWidth: 1,
    borderColor: '#9F9F9F',
    width: 15,
    height: 15,
    borderRadius: 7.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  view12: {
    display: 'none',
    width: 7.5,
    height: 7.5,
    borderRadius: 3.75,
    backgroundColor: '#6A4029',
  },
  view13: {
    position: 'absolute',
    top: '40%',
    alignSelf: 'center',
    width: 346,
    backgroundColor: '#FFFFFF',
    zIndex: 1,
    paddingLeft: 42,
    paddingRight: 42,
    paddingTop: 39,
    paddingBottom: 31,
    borderRadius: 20,
    alignItems: 'center',
  },
  view14: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  input1: {
    alignSelf: 'flex-start',
    paddingBottom: 11,
    borderBottomColor: '#9F9F9F',
    borderBottomWidth: 1,
    marginBottom: 27,
    width: '100%',
  },
  input2: {
    alignSelf: 'flex-start',
    paddingBottom: 11,
    borderBottomColor: '#9F9F9F',
    borderBottomWidth: 1,
    marginBottom: 21,
    width: '100%',
  },
  input3: {
    alignSelf: 'flex-start',
    paddingBottom: 11,
    borderBottomColor: '#9F9F9F',
    borderBottomWidth: 1,
    marginBottom: 62,
    width: '100%',
  },
  text1: {
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
    color: '#000000',
  },
  text2: {
    alignSelf: 'flex-start',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 20,
    color: '#9F9F9F',
    marginBottom: 11,
  },
  text3: {
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 19.5,
    color: '#000000',
    marginRight: 34,
  },
  text4: {
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 20,
    color: '#F6F6F9',
  },
  text5: {
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 22,
    color: '#000000',
    marginBottom: 33,
  },
  text6: {fontWeight: '700', fontSize: 15, lineHeight: 22.5, color: '#FFFFFF'},
  image1: {width: 24, height: 24},
  image2: {width: 130, height: 130, borderRadius: 65},
  image3: {width: 17, height: 17},
  image4: {
    width: 20,
    height: 20,
    right: 20,
    bottom: 10,
  },
  btn1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 70,
    backgroundColor: '#6A4029',
    borderRadius: 20,
  },
  btn2: {
    width: 105,
    height: 43,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6A4029',
    borderRadius: 10,
  },
  btn3: {position: 'absolute', top: 25, left: 25},
});

export default styles;
