import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 41,
    paddingTop: 60,
    paddingLeft: 50,
    paddingRight: 50,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 9,
  },
  view4: {
    width: 8,
    height: 8,
    backgroundColor: '#6A4029',
    borderRadius: 4,
    marginRight: 12,
  },
  view5: {
    width: 8,
    height: 8,
    backgroundColor: '#C4C4C4',
    borderRadius: 4,
    marginRight: 12,
  },
  view6: {flexDirection: 'row', marginBottom: 18},
  view7: {
    width: 8,
    height: 8,
    backgroundColor: '#C4C4C4',
    borderRadius: 4,
  },
  view8: {flexDirection: 'row', marginBottom: 30},
  view9: {flexDirection: 'row', marginBottom: 22},
  text1: {
    alignSelf: 'flex-start',
    color: '#000000',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 51,
    marginBottom: 8,
  },
  text2: {
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    paddingBottom: 4,
    borderBottomColor: '#6A4029',
    borderBottomWidth: 3,
    marginRight: 29,
  },
  text3: {
    marginRight: 29,
    color: '#9A9A9D',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    paddingBottom: 4,
  },
  text4: {
    color: '#000000',
    fontWeight: '900',
    fontSize: 28,
    lineHeight: 42,
    marginBottom: 3,
  },
  text5: {
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 33,
    color: '#6A4029',
    marginBottom: 41,
  },
  text6: {
    alignSelf: 'flex-start',
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#000000',
    marginBottom: 1,
  },
  text7: {
    alignSelf: 'flex-start',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 20.83,
    color: '#000000',
    letterSpacing: 0.02,
    marginBottom: 30,
    paddingBottom: 6,
    borderBottomColor: '#C4C4C4',
    borderBottomWidth: 1,
    width: '100%',
  },
  text8: {
    alignSelf: 'flex-start',
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#000000',
    marginBottom: 3,
  },
  text9: {
    alignSelf: 'flex-start',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 20.83,
    color: '#000000',
    letterSpacing: 0.02,
    marginBottom: 30,
    paddingBottom: 6,
    borderBottomColor: '#C4C4C4',
    borderBottomWidth: 1,
    width: '100%',
  },
  text10: {
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#F6F6F9',
  },
  text11: {
    fontWeight: '700',
    fontSize: 30,
    lineHeight: 35.16,
    color: '#FFFFFF',
  },
  input1: {
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 26,
    color: '#000000',
    opacity: 0.5,
  },
  image1: {width: 24, height: 24},
  image2: {width: 24, height: 24},
  image3: {
    width: 241.21,
    height: 241.21,
    borderRadius: 120.605,
    marginBottom: 37.79,
  },
  image4: {width: 17, height: 17},
  btn1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 314,
    height: 70,
    backgroundColor: '#6A4029',
    borderRadius: 20,
  },
  btn2: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6A4029',
    position: 'absolute',
    right: 0,
    bottom: 52,
  },
});

export default styles;
