import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 47,
    paddingTop: 65,
    paddingLeft: 50,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 33,
    paddingRight: 41,
  },
  view4: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    width: 314,
    height: 60,
    backgroundColor: '#EFEEEE',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 35,
    paddingRight: 35,
    marginBottom: 46,
  },
  view5: {
    marginBottom: 45,
  },
  view6: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 58,
    marginTop: 52,
  },
  view7: {flexDirection: 'row'},
  view8: {marginBottom: 36, height: 310},
  view9: {marginBottom: 42, height: 310},
  view10: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 47,
  },
  text1: {
    alignSelf: 'flex-start',
    color: '#000000',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 51,
    marginBottom: 8,
  },
  text2: {
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    paddingBottom: 4,
    borderBottomColor: '#6A4029',
    borderBottomWidth: 3,
    marginRight: 29,
  },
  text3: {
    marginRight: 29,
    color: '#9A9A9D',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    paddingBottom: 4,
  },
  text4: {
    alignSelf: 'flex-end',
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    marginRight: 27,
    marginLeft: 10,
  },
  text5: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
    color: '#9A9A9D',
    marginLeft: 16,
    marginRight: 16,
  },
  text6: {
    alignSelf: 'flex-start',
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    paddingBottom: 4,
    borderBottomColor: '#6A4029',
    borderBottomWidth: 3,
    marginBottom: 47,
  },
  text7: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
    lineHeight: 22.5,
  },
  text8: {
    alignSelf: 'center',
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    marginRight: 27,
    marginBottom: 47,
  },
  text9: {
    alignSelf: 'flex-end',
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    marginRight: 27,
    marginLeft: 10,
  },
  input1: {
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 26,
    color: '#000000',
    opacity: 0.5,
  },
  image1: {width: 22, height: 14.67},
  image2: {width: 24, height: 24},
  image3: {width: 18, height: 18, marginRight: 16},
  image4: {width: 24.76, height: 24.8},
  image5: {width: 24, height: 24, marginRight: 68},
  image6: {width: 23, height: 23},
  btn1: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    alignItems: 'center',
    width: 306,
    height: 58,
    backgroundColor: '#6A4029',
    borderRadius: 20,
    marginBottom: 11,
  },
  btn2: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderWidth: 1,
    borderColor: 'rgba(137, 85, 55, 1)',
  },
  btn3: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: 'rgba(255, 186, 51, 1)',
    borderWidth: 1,
    borderColor: 'rgba(137, 85, 55, 1)',
  },
});

export default styles;
