import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 53,
    paddingTop: 113,
    paddingLeft: 31,
    paddingRight: 31,
  },
  view3: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 33,
  },
  text1: {
    position: 'absolute',
    width: 146,
    top: '30%',
    left: '30%',
    color: '#000000',
    fontWeight: '700',
    fontSize: 65,
    lineHeight: 56.44,
  },
  text2: {
    alignSelf: 'flex-start',
    color: '#895537',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 22,
    textDecorationLine: 'underline',
  },
  text3: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
  text4: {
    color: '#000000',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    marginLeft: 14.38,
  },
  text5: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
    color: '#9A9A9D',
    marginLeft: 16,
    marginRight: 16,
  },
  input1: {
    width: 352,
    borderBottomWidth: 1,
    borderBottomColor: '#9F9F9F',
    paddingBottom: 6,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 28,
    color: '#9A9A9D',
  },
  input2: {
    width: 352,
    borderBottomWidth: 1,
    borderBottomColor: '#9F9F9F',
    paddingBottom: 6,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 23,
    color: '#9A9A9D',
  },
  image1: {right: 44, marginBottom: 30, width: 165, height: 328},
  btn1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 352,
    height: 70,
    backgroundColor: '#6A4029',
    borderRadius: 20,
    marginBottom: 33,
  },
  btn2: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 352,
    height: 70,
    backgroundColor: '#FFFFFF',
    borderColor: '#C7C7C7',
    borderWidth: 1,
    borderRadius: 20,
  },
  btn3: {alignSelf: 'flex-start'},
});

export default styles;
