import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 58,
    paddingTop: 60,
    paddingLeft: 41,
    paddingRight: 57,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 44,
  },
  view4: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(186, 186, 186, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 17,
  },
  view5: {
    bottom: 12,
    right: 0,
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#6A4029',
    justifyContent: 'center',
    alignItems: 'center',
  },
  text1: {
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 30,
    color: '#000000',
    marginLeft: 83,
  },
  text2: {
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#000000',
    marginBottom: 0,
    alignSelf: 'flex-start',
  },
  text3: {
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#F6F6F9',
  },
  text4: {
    fontWeight: '700',
    fontSize: 30,
    lineHeight: 35.16,
    color: '#FFFFFF',
  },
  input1: {
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 15,
    color: '#9F9F9F',
    paddingBottom: 9.25,
    borderBottomColor: '#C4C4C4',
    borderBottomWidth: 1,
    width: '100%',
    marginBottom: 14.75,
  },
  input2: {
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 15,
    color: '#9F9F9F',
    paddingBottom: 9.25,
    borderBottomColor: '#C4C4C4',
    borderBottomWidth: 1,
    width: '100%',
    marginBottom: 46,
  },
  image1: {width: 24, height: 24},
  image2: {width: 53, height: 50},
  image3: {width: 200, height: 200, borderRadius: 100},
  btn1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 70,
    backgroundColor: '#6A4029',
    borderRadius: 20,
  },
});

export default styles;
