import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view: {
    backgroundColor: '#F2F2F2',
  },
  view1: {width: 87, height: 0, borderWidth: 1, borderColor: '#9F9F9F'},
  view2: {
    alignItems: 'center',
    paddingBottom: 58,
    paddingTop: 60,
    paddingLeft: 41,
    paddingRight: 57,
  },
  view3: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 40,
  },
  view4: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 9,
  },
  view5: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 24,
    paddingTop: 26,
    paddingLeft: 23,
    paddingRight: 23,
    paddingBottom: 26,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    shadowColor: '#00000008',
    shadowOpacity: 0.03,
    textShadowOffset: {width: 0, height: 10},
    shadowRadius: 40,
  },
  view6: {
    width: 170.01,
  },
  view7: {flexDirection: 'row', marginBottom: 25, alignItems: 'center'},
  view8: {
    borderWidth: 1,
    borderColor: '#6A4029',
    width: 15,
    height: 15,
    borderRadius: 7.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  view9: {
    width: 7.5,
    height: 7.5,
    borderRadius: 3.75,
    backgroundColor: '#6A4029',
  },
  view10: {
    borderWidth: 1,
    borderColor: '#9F9F9F',
    width: 15,
    height: 15,
    borderRadius: 7.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  view11: {flexDirection: 'row'},
  view12: {
    display: 'none',
    width: 7.5,
    height: 7.5,
    borderRadius: 3.75,
    backgroundColor: '#6A4029',
  },
  view13: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 23,
  },
  view14: {
    width: 40,
    height: 40,
    backgroundColor: '#F47B0A',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 11,
  },
  view15: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 15,
    borderBottomColor: 'rgba(0, 0, 0, 1)',
    borderBottomWidth: 0.5,
    width: 232,
  },
  view16: {
    width: 40,
    height: 40,
    backgroundColor: '#895537',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 11,
  },
  view17: {
    width: 40,
    height: 40,
    backgroundColor: '#FFBA33',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 11,
  },
  view18: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 232,
  },
  text1: {
    alignSelf: 'flex-start',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 51,
    color: '#000000',
    marginBottom: 30,
  },
  text2: {
    alignSelf: 'flex-start',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 51,
    color: '#000000',
    marginBottom: 35,
  },
  text3: {
    color: '#000000',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
  },
  text4: {
    color: '#6A4029',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22.5,
  },
  text5: {
    color: '#000000',
    fontWeight: '900',
    fontSize: 18,
    lineHeight: 27,
    marginBottom: 8,
  },
  text6: {
    color: '#6A4029',
    opacity: 0.6,
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    paddingBottom: 1,
    borderBottomColor: '#000000',
    borderBottomWidth: 0.5,
    marginBottom: 6,
  },
  text7: {
    color: '#6A4029',
    opacity: 0.6,
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
  },
  text8: {
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
    color: '#000000',
  },
  text9: {
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
    color: '#000000',
  },
  text10: {
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#000000',
  },
  text11: {
    fontWeight: '900',
    fontSize: 22,
    lineHeight: 33,
    color: '#000000',
  },
  text12: {
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 25.5,
    color: '#F6F6F9',
  },
  input1: {
    fontWeight: '900',
    fontSize: 17,
    lineHeight: 26,
    color: '#000000',
    opacity: 0.5,
  },
  image1: {width: 24, height: 24},
  image2: {width: 80, height: 80, borderRadius: 40, marginRight: 19},
  image3: {width: 24, height: 24},
  btn1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 70,
    backgroundColor: '#6A4029',
    borderRadius: 20,
  },
  btn2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 23,
    paddingRight: 17,
    alignItems: 'center',
    width: '100%',
    height: 60,
    backgroundColor: '#FFFFFF',
    shadowColor: 'rgba(0, 0, 0, 0.03)',
    shadowRadius: 40,
    shadowOffset: {width: 0, height: 10},
    borderRadius: 20,
    marginBottom: 27,
  },
  btn3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 23,
    paddingRight: 17,
    alignItems: 'center',
    width: '100%',
    height: 60,
    backgroundColor: '#FFFFFF',
    shadowColor: 'rgba(0, 0, 0, 0.03)',
    shadowRadius: 40,
    shadowOffset: {width: 0, height: 10},
    borderRadius: 20,
    marginBottom: 34,
  },
});

export default styles;
